# Generated by Django 5.2.6 on 2025-09-10 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_organizer_text_to_fk(apps, schema_editor):
    Event = apps.get_model('admin_app', 'Event')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    for event in Event.objects.all():
        organizer_text = getattr(event, 'organizer', None)
        if organizer_text is None:
            continue
        user, _ = User.objects.get_or_create(username=str(organizer_text)[:150])
        setattr(event, 'organizer_new', user)
        event.save(update_fields=['organizer_new'])


def reverse_migrate_organizer_fk_to_text(apps, schema_editor):
    Event = apps.get_model('admin_app', 'Event')
    for event in Event.objects.select_related('organizer_new').all():
        user = getattr(event, 'organizer_new', None)
        if user is None:
            continue
        setattr(event, 'organizer', user.username)
        event.save(update_fields=['organizer'])


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='available_tickets',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='open_for_booking',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='venue',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='price_per_ticket',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(),
        ),
        # Organizer CharField -> FK via temporary field and data migration
        migrations.AddField(
            model_name='event',
            name='organizer_new',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(migrate_organizer_text_to_fk, reverse_migrate_organizer_fk_to_text),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer_new',
            new_name='organizer',
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
