# Generated by Django 5.2.6 on 2025-09-13 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'time'], name='event_active_time_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['time'], name='event_time_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active'], name='event_active_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue'], name='event_venue_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['price_per_ticket'], name='event_price_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='event_created_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='event_organizer_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'time', 'created_at'], name='event_composite_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', 'venue'], name='event_active_venue_idx'),
        ),
    ]
