# Generated by Django 5.2.6 on 2025-09-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='task_id',
            field=models.CharField(blank=True, help_text='Celery task ID for async processing', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('processing', 'Processing'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], max_length=20),
        ),
    ]
