# Generated by Django 5.2.6 on 2025-09-13 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_add_database_indexes'),
        ('booking', '0018_booking_task_id_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('processing', 'Processing')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event', 'status'], name='booking_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user'], name='booking_user_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'booking_date'], name='booking_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='booking_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['task_id'], name='booking_task_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event', 'user', 'status'], name='booking_event_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'booking_date'], name='booking_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['event', 'status'], name='booking_availability_idx'),
        ),
    ]
